apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-rr0j
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-rr0j
    app.kubernetes.io/part-of: tkrw-pr714-0075-0004-app
  name: devfile-sample-rr0j
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-rr0j
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-rr0j
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0004-tenant/tkrw-pr714-0075-0004-app/devfile-sample-rr0j@sha256:08a3a2a6a6d33a21284f2e1e5674fa0cc9cc925ad318c917d12c78a8a1fea924
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
